name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: |
          git config --global user.name "vehidtr"
          git config --global user.email "vehid.trtak@gmail.com"

          npm run build:docs

          git add .
          git commit -m "Testing build"
          git push
